name: Run Telegram Bot

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install libraries
        run: pip install -r requirements.txt

      - name: Run bot
        run: python bot.py
        env:
          BOT_TOKEN: ${{ 8669478332:AAEchKpc1C9D27Nkr1Zr0tscyiI_q3nMIuI }}
          GEMINI_API: ${{ AIzaSyCu_KkHr2JKW3Hiv78xsye5d3K9Jp5XVLs }}
